name: "@NAME@"
version: "@VERSION@"
main: "@PACKAGE@.Echolite"
api-version: "1.21"
description: "Minecraft–Discord chat bridge with rich formatting, slash commands, and status updates."
website: "https://github.com/walker84837/Echolite"
loader: "@PACKAGE@.EcholiteLoader"
folia-supported: true
